/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package bi.assignment;

import java.io.File;
import java.io.IOException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;
import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;

public class App {

    public static ChromeDriver createDriver() {
        // TODO Create a new chrome Driver and Return the same

        WebDriverManager.chromedriver().setup();

        ChromeDriver driver;
        driver = new ChromeDriver();
        return driver;
    }

    public static void printQKartLoadingtime(ChromeDriver driver) {
        // TODO Navigate to home page of QKart and verify the time taken for the page to
        // load

        long strtime = System.currentTimeMillis();
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        long endtime = System.currentTimeMillis();
        long loadingtime = strtime - endtime;
        System.out.println("Time requried for loading webpage is: " + loadingtime / 1000);
    }

    public static void captureFullPageScreenshot(ChromeDriver driver) {
        // TODO: Capture the full page screenshot
        // Save the file with a unique name
        // Print the path of the file
        // try {
        // File theDir = new File("/screenshots");
        // if (!theDir.exists()) {
        // theDir.mkdirs();
        // }

        // String timestamp = String.valueOf(java.time.LocalDateTime.now());
        // String fileName = String.format("screenshot_%s_%s_%s.png", timestamp,
        // screenshotType, description);

        // TakesScreenshot scrShot = ((TakesScreenshot) driver);
        // File SrcFile = scrShot.getScreenshotAs(OutputType.FILE);

        // File DestFile = new File("screenshots/" + fileName);
        // FileUtils.copyFile(SrcFile, DestFile);
        // } catch (Exception e) {
        // e.printStackTrace();
        // }
        Screenshot screenshot = new AShot()
                .shootingStrategy(ShootingStrategies.viewportPasting(100))
                .takeScreenshot(driver);
        try {
            ImageIO.write(screenshot.getImage(), "PNG", new File("FullPageScreenshot1.png"));
        } catch (IOException e) {

            e.printStackTrace();
        }
    }

    public static void GetProductImageandURL(ChromeDriver driver, String productName) throws InterruptedException {
        // TODO: Given the product name, print the price of the project and the url of
        // the image
        boolean status = true;
        WebElement searchBox = driver.findElement(By.name("search"));
        searchBox.clear();
        searchBox.sendKeys(productName);
        try {
            Thread.sleep(3000);
        } catch (Exception e) {
            System.out.println("Interrupted exception");
        }
        WebElement product = driver.findElement(By.xpath("//div[@class='MuiCardContent-root css-1qw96cp']"));
        String prroduct_ = product.getText();
        Thread.sleep(20000);
        System.out.println(prroduct_);

        String price = driver
                .findElement(By.xpath("//p[@class='MuiTypography-root MuiTypography-body1 css-uickyz']"))
                .getText();
        WebElement urlimg = driver.findElement(
                By.xpath("//img[@class='MuiCardMedia-root MuiCardMedia-media MuiCardMedia-img css-rhsghg']"));
        String urlOfimg = urlimg.getAttribute("src");
        if (prroduct_.contains(productName)) {

            System.out.println(" image URL " + "" + urlOfimg);
            System.out.println("Price of product is :" + price);
        }

    }

    public static void main(String[] args) {
        ChromeDriver driver = createDriver();
        String input = String.join(" ", args);
        try {

            printQKartLoadingtime(driver);

            captureFullPageScreenshot(driver);

            GetProductImageandURL(driver, input);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            driver.quit();
        }
    }
}